plugins {
    id 'java'
    id 'checkstyle'
}

repositories {
    mavenLocal()
    maven { url = 'https://repo.runelite.net' }
    mavenCentral()
}

def runeLiteVersion = 'latest.release'

dependencies {
    compileOnly group: 'net.runelite', name: 'client', version: runeLiteVersion
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    testImplementation files('../420kcp/build/libs/420-kc-plugin-1.0.0.jar')
    testImplementation 'junit:junit:4.13.2'
    testImplementation group: 'net.runelite', name: 'client', version: runeLiteVersion
    testImplementation group: 'net.runelite', name: 'jshell', version: runeLiteVersion
    testCompileOnly 'org.projectlombok:lombok:1.18.30'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
}

group = 'com.killclog'
version = '1.0.0'
sourceCompatibility = '11'
targetCompatibility = '11'

checkstyle {
    toolVersion = '8.25'
    configDirectory = file("config/checkstyle")
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

task run(type: JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'com.killclog.KillClogPluginTest'
    jvmArgs = ['-ea']
}
