displayName=Kill Clog
author=420 kc
support=https://github.com/420kc/kill-clog-plugin/issues
description=Kills. Clogs. Colors.
tags=boss,kc,kill count,collection log,pvm,hiscore,ironman
plugins=com.killclog.KillClogPlugin
build=gradle
