displayName=Kill Clog
author=420 kc
support=https://github.com/420kc/kill-clog-plugin/issues
description=HiScores and Collection Log Overhaul
tags=boss,kc,kill count,collection log,pvm,hiscore,ironman,comparison,runeprofile,combat achievements
plugins=com.killclog.KillClogPlugin
build=standard
version=1.7.0
